### ISSUE TITLE
CosaShell : won't compile (arduino 1.0.6)

### ISSUE THREAD

**Issue by guiguid** [mikaelpatel/Cosa#278]
Load example: CosaShell and compile with arduino 1.0.6 & board Cosa Duemilanove

Commands.cpp:662: error: init_tab causes a section type conflict
Commands.cpp:661: error: INIT_PROMPT causes a section type conflict
Commands.cpp:652: error: __c causes a section type conflict
Commands.cpp:650: error: __c causes a section type conflict
Commands.cpp:644: error: __c causes a section type conflict
Commands.cpp:641: error: __c causes a section type conflict
Commands.cpp:592: error: __c causes a section type conflict
Commands.cpp:591: error: __c causes a section type conflict
Commands.cpp:590: error: __c causes a section type conflict
Commands.cpp:581: error: __c causes a section type conflict
Commands.cpp:551: error: __c causes a section type conflict
Commands.cpp:540: error: __c causes a section type conflict
Commands.cpp:539: error: __c causes a section type conflict
Commands.cpp:538: error: __c causes a section type conflict
Commands.cpp:536: error: __c causes a section type conflict
Commands.cpp:525: error: __c causes a section type conflict
Commands.cpp:523: error: __c causes a section type conflict
Commands.cpp:521: error: __c causes a section type conflict
Commands.cpp:520: error: __c causes a section type conflict
Commands.cpp:507: error: __c causes a section type conflict
Commands.cpp:476: error: __c causes a section type conflict
Commands.cpp:463: error: __c causes a section type conflict
Commands.cpp:461: error: __c causes a section type conflict
Commands.cpp:459: error: __c causes a section type conflict
Commands.cpp:445: error: __c causes a section type conflict
Commands.cpp:436: error: __c causes a section type conflict
Commands.cpp:435: error: __c causes a section type conflict
Commands.cpp:422: error: __c causes a section type conflict
Commands.cpp:420: error: __c causes a section type conflict
Commands.cpp:418: error: __c causes a section type conflict
Commands.cpp:401: error: __c causes a section type conflict
Commands.cpp:372: error: __c causes a section type conflict
Commands.cpp:359: error: __c causes a section type conflict
Commands.cpp:357: error: __c causes a section type conflict
Commands.cpp:245: error: __c causes a section type conflict
Commands.cpp:219: error: __c causes a section type conflict
Commands.cpp:190: error: __c causes a section type conflict
Commands.cpp:182: error: __c causes a section type conflict
Commands.cpp:181: error: __c causes a section type conflict
Commands.cpp:308: error: __c causes a section type conflict
Commands.cpp:279: error: __c causes a section type conflict
Commands.cpp:277: error: __c causes a section type conflict
Commands.cpp:94: error: __c causes a section type conflict
Commands.cpp:92: error: __c causes a section type conflict
Commands.cpp:92: error: __c causes a section type conflict
Commands.cpp:61: error: __c causes a section type conflict
Commands.cpp:53: error: __c causes a section type conflict
Commands.cpp:52: error: __c causes a section type conflict
Commands.cpp:100: error: blink_SCRIPT causes a section type conflict
Commands.cpp:49: error: analogread_NAME causes a section type conflict
Commands.cpp:49: error: analogread_ARGS causes a section type conflict
Commands.cpp:49: error: analogread_HELP causes a section type conflict
Commands.cpp:85: error: args_NAME causes a section type conflict
Commands.cpp:85: error: args_ARGS causes a section type conflict
Commands.cpp:85: error: args_HELP causes a section type conflict
Commands.cpp:100: error: blink_NAME causes a section type conflict
Commands.cpp:100: error: blink_ARGS causes a section type conflict
Commands.cpp:100: error: blink_HELP causes a section type conflict
Commands.cpp:121: error: date_NAME causes a section type conflict
Commands.cpp:121: error: date_ARGS causes a section type conflict
Commands.cpp:121: error: date_HELP causes a section type conflict
Commands.cpp:165: error: delay_NAME causes a section type conflict
Commands.cpp:165: error: delay_ARGS causes a section type conflict
Commands.cpp:165: error: delay_HELP causes a section type conflict
Commands.cpp:264: error: dump_NAME causes a section type conflict
Commands.cpp:264: error: dump_ARGS causes a section type conflict
Commands.cpp:264: error: dump_HELP causes a section type conflict
Commands.cpp:300: error: echo_NAME causes a section type conflict
Commands.cpp:300: error: echo_ARGS causes a section type conflict
Commands.cpp:300: error: echo_HELP causes a section type conflict
Commands.cpp:319: error: epoch_NAME causes a section type conflict
Commands.cpp:319: error: epoch_ARGS causes a section type conflict
Commands.cpp:319: error: epoch_HELP causes a section type conflict
Commands.cpp:178: error: digitalread_NAME causes a section type conflict
Commands.cpp:178: error: digitalread_ARGS causes a section type conflict
Commands.cpp:178: error: digitalread_HELP causes a section type conflict
Commands.cpp:213: error: digitaltoggle_NAME causes a section type conflict
Commands.cpp:213: error: digitaltoggle_ARGS causes a section type conflict
Commands.cpp:213: error: digitaltoggle_HELP causes a section type conflict
Commands.cpp:237: error: digitalwrite_NAME causes a section type conflict
Commands.cpp:237: error: digitalwrite_ARGS causes a section type conflict
Commands.cpp:237: error: digitalwrite_HELP causes a section type conflict
Commands.cpp:333: error: help_NAME causes a section type conflict
Commands.cpp:333: error: help_ARGS causes a section type conflict
Commands.cpp:333: error: help_HELP causes a section type conflict
Commands.cpp:342: error: idle_NAME causes a section type conflict
Commands.cpp:342: error: idle_ARGS causes a section type conflict
Commands.cpp:342: error: idle_HELP causes a section type conflict
Commands.cpp:352: error: led_NAME causes a section type conflict
Commands.cpp:352: error: led_ARGS causes a section type conflict
Commands.cpp:352: error: led_HELP causes a section type conflict
Commands.cpp:330: error: logout_NAME causes a section type conflict
Commands.cpp:330: error: logout_ARGS causes a section type conflict
Commands.cpp:330: error: logout_HELP causes a section type conflict
Commands.cpp:366: error: memory_NAME causes a section type conflict
Commands.cpp:366: error: memory_ARGS causes a section type conflict
Commands.cpp:366: error: memory_HELP causes a section type conflict
Commands.cpp:376: error: micros_NAME causes a section type conflict
Commands.cpp:376: error: micros_ARGS causes a section type conflict
Commands.cpp:376: error: micros_HELP causes a section type conflict
Commands.cpp:386: error: millis_NAME causes a section type conflict
Commands.cpp:386: error: millis_ARGS causes a section type conflict
Commands.cpp:386: error: millis_HELP causes a section type conflict
Commands.cpp:396: error: owi_NAME causes a section type conflict
Commands.cpp:396: error: owi_ARGS causes a section type conflict
Commands.cpp:396: error: owi_HELP causes a section type conflict
Commands.cpp:427: error: pinmode_NAME causes a section type conflict
Commands.cpp:427: error: pinmode_ARGS causes a section type conflict
Commands.cpp:427: error: pinmode_HELP causes a section type conflict
Commands.cpp:472: error: repeat_NAME causes a section type conflict
Commands.cpp:472: error: repeat_ARGS causes a section type conflict
Commands.cpp:472: error: repeat_HELP causes a section type conflict
Commands.cpp:511: error: stty_NAME causes a section type conflict
Commands.cpp:511: error: stty_ARGS causes a section type conflict
Commands.cpp:511: error: stty_HELP causes a section type conflict
Commands.cpp:546: error: tone_NAME causes a section type conflict
Commands.cpp:546: error: tone_ARGS causes a section type conflict
Commands.cpp:546: error: tone_HELP causes a section type conflict
Commands.cpp:576: error: twi_NAME causes a section type conflict
Commands.cpp:576: error: twi_ARGS causes a section type conflict
Commands.cpp:576: error: twi_HELP causes a section type conflict
Commands.cpp:597: error: uptime_NAME causes a section type conflict
Commands.cpp:597: error: uptime_ARGS causes a section type conflict
Commands.cpp:597: error: uptime_HELP causes a section type conflict
Commands.cpp:635: error: login_NAME causes a section type conflict
Commands.cpp:635: error: login_ARGS causes a section type conflict
Commands.cpp:635: error: login_HELP causes a section type conflict
